# 工作经历列表（按时间倒序）
jobs:
  - company: ZTE
    position: 基带软件开发工程师
    location: 深圳
    start_date: 2025 Aug
    end_date: now
    current: true
    description: |
         - to be added
    highlights:
         - to be added

  # - company: 某创业科技公司
  #   position: 前端开发工程师
  #   location: 上海
  #   start_date: 2018-07
  #   end_date: 2021-02
  #   current: false
  #   description: |
  #     作为早期员工参与产品从 0 到 1 的开发。
  #   highlights:
  #     - 独立完成移动端 H5 应用开发，日活用户 10万+
  #     - 优化首屏加载时间，从 3s 降至 1.2s
  #     - 实现复杂的动画交互效果，提升用户体验
