# 工作经历列表（按时间倒序）
jobs:
  - company: ZTE
    position: 基带软件开发
    location: 深圳
    start_date: 2025 Aug
    end_date: now
    current: true
    description: 
     • 从事公司自研硬件的集合通信库（类NCCL）的开发，包括在网计算INC和RDMA相关的功能接入 <br>
     • 从事公司自研的交换芯片IP的verbs接口与GPU IP的功能联调以及性能评估和优化 <br>
     • 从事公司自研硬件在集合通信级别的Palladium仿真环境下硬件性能测试的功能代码开发和性能测试评估，包括MLA和MLP等经典前向传播场景下的数据流和硬件资源的调度 <br>
     • 深度参与P到A阶段芯片级集合通信资源调度方案设计，覆盖多级缓存复用策略与DMA数据流编排，输出硅后Device侧数据流与Buffer复用方案的工程代码
#     highlights:
#          - to be added

  # - company: 某创业科技公司
  #   position: 前端开发工程师
  #   location: 上海
  #   start_date: 2018-07
  #   end_date: 2021-02
  #   current: false
  #   description: |
  #     作为早期员工参与产品从 0 到 1 的开发。
  #   highlights:
  #     - 独立完成移动端 H5 应用开发，日活用户 10万+
  #     - 优化首屏加载时间，从 3s 降至 1.2s
  #     - 实现复杂的动画交互效果，提升用户体验
